// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzaddteGMpfBhJvyqUqqR6SBxOIee6v4',
    appId: '1:903244681:web:ed3aa00eb16784ad230f58',
    messagingSenderId: '903244681',
    projectId: 'flight-booking-f5d6e',
    authDomain: 'flight-booking-f5d6e.firebaseapp.com',
    storageBucket: 'flight-booking-f5d6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCssdObvfrGWQMHgurUQBBGGpEhZJWEYBQ',
    appId: '1:903244681:android:a733e239f51ec3f6230f58',
    messagingSenderId: '903244681',
    projectId: 'flight-booking-f5d6e',
    storageBucket: 'flight-booking-f5d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0uovy4iaAvihuqLfO9LBoIB-j7VDLgk',
    appId: '1:903244681:ios:b4975c5014915071230f58',
    messagingSenderId: '903244681',
    projectId: 'flight-booking-f5d6e',
    storageBucket: 'flight-booking-f5d6e.appspot.com',
    androidClientId: '903244681-pjupm2gd0si2b0n5o3cbeboarsqk1rct.apps.googleusercontent.com',
    iosClientId: '903244681-ep4kogg685b770rmng1e0737kksoajti.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG0uovy4iaAvihuqLfO9LBoIB-j7VDLgk',
    appId: '1:903244681:ios:b4975c5014915071230f58',
    messagingSenderId: '903244681',
    projectId: 'flight-booking-f5d6e',
    storageBucket: 'flight-booking-f5d6e.appspot.com',
    androidClientId: '903244681-pjupm2gd0si2b0n5o3cbeboarsqk1rct.apps.googleusercontent.com',
    iosClientId: '903244681-ep4kogg685b770rmng1e0737kksoajti.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmzaddteGMpfBhJvyqUqqR6SBxOIee6v4',
    appId: '1:903244681:web:ff822592979aca16230f58',
    messagingSenderId: '903244681',
    projectId: 'flight-booking-f5d6e',
    authDomain: 'flight-booking-f5d6e.firebaseapp.com',
    storageBucket: 'flight-booking-f5d6e.appspot.com',
  );
}
